import Head from 'next/head';

// Components
import Main from '../components/Main';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Brandetize Web Dev Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://use.typekit.net/juo8ten.css"/>
      </Head>

      <main>
        <Main />
      </main>

    </div>
  )
}
