import Head from 'next/head';

// Components
import Main from '../components/Main';
import About from '../components/About';
import Founder from '../components/Founder';
import Collapsable from '../components/Collapsable';
import Testimonials from '../components/Testimonials';
import Agenda from '../components/Agenda';
import Footer from '../components/Footer';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Brandetize Web Dev Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Main />
        <About />
        <Founder />
        <Collapsable />
        <Testimonials />
        <Agenda />
        <Footer />
      </main>

    </div>
  )
}
