import Head from 'next/head';

// Components
import Main from '../components/Main';
import About from '../components/About';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Brandetize Web Dev Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Main />
        <About />
      </main>

    </div>
  )
}
